//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace whistle_mouse.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("whistle_mouse.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu 123;TOOL BOX;T_BOX
        ///111;LEFT MOUSE CLICK 2x;MOUSE_CLICK/*/MOUSE_CLICK
        /////;;************************
        ///T_BOX;CORD X100,Y100;CORD-100,100
        ///T_BOX;MUTE;MUTE
        ///T_BOX;WHISTLE-MOUSE;SENDKEY-WHISTLE MOUSE
        ///T_BOX;OPEN NOTEPAD;FILE-NOTEPAD
        ///.
        /// </summary>
        internal static string function {
            get {
                return ResourceManager.GetString("function", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu //;;Mouse function parametr****************************
        ///1;LNG_1;BACKWARD
        ///2;LNG_2;FORWARD
        ///3;LNG_3;STANDBY
        ///12;LNG_4;FLIP
        ///21;LNG_5;SCROLL
        ///32;LNG_6;MOUSE_CLICK
        ///323;LNG_7;DOUBLE_MOUSE_CLICK
        ///321;LNG_11;RIGHT_MOUSE_CLICK
        ///3232;LNG_8;MOUSE_CLICK_HOLD
        ///121;LNG_9;MAX_BACKWARD
        ///212;LNG_10;MAX_FORWARD
        /////;;************************************************************
        /////;;Function time parametr**********************************
        ///F_TIME;FRQ3_LONG;35
        ///F_TIME;FRQ_SHORT;20
        ///F_TIME;FRQ_TIMER;45
        /////;;***************** [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string program_function {
            get {
                return ResourceManager.GetString("program_function", resourceCulture);
            }
        }
    }
}
